
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.aws-lc-rs]]
version = "1.16.3"
criteria = "safe-to-deploy"

[[exemptions.aws-lc-sys]]
version = "0.40.0"
criteria = "safe-to-deploy"

[[exemptions.backtrace-ext]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.clap-markdown]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.combine]]
version = "4.6.7"
criteria = "safe-to-deploy"

[[exemptions.console]]
version = "0.16.3"
criteria = "safe-to-run"

[[exemptions.core-foundation]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-deque]]
version = "0.8.6"
criteria = "safe-to-run"

[[exemptions.crossbeam-utils]]
version = "0.8.21"
criteria = "safe-to-run"

[[exemptions.deadpool-runtime]]
version = "0.1.4"
criteria = "safe-to-run"

[[exemptions.dunce]]
version = "1.0.5"
criteria = "safe-to-deploy"

[[exemptions.encode_unicode]]
version = "1.0.0"
criteria = "safe-to-run"

[[exemptions.fs_extra]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.globwalk]]
version = "0.9.1"
criteria = "safe-to-run"

[[exemptions.humansize]]
version = "2.1.3"
criteria = "safe-to-deploy"

[[exemptions.jni]]
version = "0.22.4"
criteria = "safe-to-deploy"

[[exemptions.jni-macros]]
version = "0.22.4"
criteria = "safe-to-deploy"

[[exemptions.jni-sys]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.jni-sys-macros]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.lru-slab]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.miette]]
version = "7.6.0"
criteria = "safe-to-deploy"

[[exemptions.miette-derive]]
version = "7.6.0"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "8.0.0"
criteria = "safe-to-deploy"

[[exemptions.num-format]]
version = "0.4.4"
criteria = "safe-to-deploy"

[[exemptions.openssl-probe]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic]]
version = "1.13.1"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic-util]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.21"
criteria = "safe-to-deploy"

[[exemptions.quinn]]
version = "0.11.9"
criteria = "safe-to-deploy"

[[exemptions.quinn-proto]]
version = "0.11.14"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "6.0.0"
criteria = "safe-to-run"

[[exemptions.rustls-native-certs]]
version = "0.8.3"
criteria = "safe-to-deploy"

[[exemptions.rustls-platform-verifier]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-platform-verifier-android]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "3.7.0"
criteria = "safe-to-deploy"

[[exemptions.simd_cesu8]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.simdutf8]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.stable_deref_trait]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.supports-color]]
version = "3.0.2"
criteria = "safe-to-deploy"

[[exemptions.supports-unicode]]
version = "3.0.0"
criteria = "safe-to-deploy"

[[exemptions.system-configuration]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.36"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.121"
criteria = "safe-to-deploy"

[[exemptions.web-time]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-util]]
version = "0.1.11"
criteria = "safe-to-deploy"

[[exemptions.windows-strings]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.60.2"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.48"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.48"
criteria = "safe-to-deploy"
